- hosts: mastodon
  become: yes
  tasks:

    - timezone:
        name: Asia/Tokyo

    - unarchive:
        remote_src: yes
        src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-245.0.0-linux-x86_64.tar.gz
        dest: /opt

    - pacman:
        update_cache: yes
        name:
          - nano
          - rsync
          - python2
          - cronie
          - docker
          - docker-compose

    - systemd:
        state: started
        enabled: yes
        name: "{{ item }}"
      loop:
        - cronie
        - docker

    - cron:
        name: backup
        minute: "30"
        hour: "4"
        job: "cd /opt/mastodon && ./backup.sh"

    - user:
        groups:
          - docker
        append: yes
        name: kaz

    - file:
        state: directory
        recurse: yes
        mode: 0777
        path: /opt/mastodon/public/system

    - copy:
        src: files/{{ item.file }}
        dest: /opt/mastodon/{{ item.file }}
        mode: "{{ item.mode }}"
      loop:
        - file: .env.production
          mode: "644"
        - file: docker-compose.yaml
          mode: "644"
        - file: nginx.conf
          mode: "644"
        - file: run.sh
          mode: "755"
        - file: backup.sh
          mode: "755"
