- hosts: mastodon
  tasks:

    - become: yes
      unarchive:
        remote_src: yes
        src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-245.0.0-linux-x86_64.tar.gz
        dest: /opt

    - become: yes
      pacman:
        update_cache: yes
        name:
          - nano
          - rsync
          - python2
          - docker
          - docker-compose

    - become: yes
      systemd:
        state: started
        enabled: yes
        name: docker

    - become: yes
      user:
        groups:
          - docker
        append: yes
        name: kaz

    - become: yes
      file:
        state: directory
        recurse: yes
        mode: 0777
        path: /opt/mastodon/public/system

    - become: yes
      copy:
        src: files/{{ item.file }}
        dest: /opt/mastodon/{{ item.file }}
        mode: "{{ item.mode }}"
      loop:
        - file: .env.production
          mode: "644"
        - file: docker-compose.yaml
          mode: "644"
        - file: nginx.conf
          mode: "644"
        - file: run.sh
          mode: "755"
