- hosts: mastodon
  become: yes
  tasks:

    - timezone:
        name: Asia/Tokyo

    - unarchive:
        remote_src: yes
        src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-281.0.0-linux-x86_64.tar.gz
        dest: /opt

    - pacman:
        update_cache: yes
        state: latest
        name: archlinux-keyring

    - pacman:
        name: "{{ item }}"
      loop:
        - cronie
        - docker
        - docker-compose
        - nano
        - python-cryptography
        - python2
        - rsync

    - systemd:
        state: started
        enabled: yes
        name: "{{ item }}"
      loop:
        - cronie
        - docker

    - cron:
        name: backup
        minute: "30"
        hour: "4"
        job: "cd /opt/mastodon && ./backup.sh"

    - user:
        groups:
          - docker
        append: yes
        name: kaz

    - file:
        state: directory
        recurse: yes
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop:
        - path: /opt/mastodon/tls
          mode: "755"
        - path: /opt/mastodon/public/system
          mode: "777"

    - template:
        src: files/{{ item.file }}
        dest: /opt/mastodon/{{ item.file }}
        mode: "{{ item.mode }}"
      loop:
        - file: .env.production
          mode: "644"
        - file: docker-compose.yaml
          mode: "644"
        - file: nginx.conf
          mode: "644"
        - file: run.sh
          mode: "755"
        - file: backup.sh
          mode: "755"

    - openssl_privatekey:
        path: /opt/mastodon/tls/key.pem
        type: ECC
        curve: secp256r1

    - openssl_csr:
        path: /opt/mastodon/tls/csr.pem
        privatekey_path: /opt/mastodon/tls/key.pem
        common_name: kiritan.com

    - openssl_certificate:
        path: /opt/mastodon/tls/crt.pem
        csr_path: /opt/mastodon/tls/csr.pem
        privatekey_path: /opt/mastodon/tls/key.pem
        provider: selfsigned
